project:
  type: website
  output-dir: docs

website:
  title: "Prabhlin Kaur Matta"
  navbar:
    background: "#fffaf7"
    foreground: "#3c2b29"
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
      - href: certifications.qmd
        text: Certifications
      - href: articles.qmd
        text: Articles


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
